- name: Create App user
  ansible.builtin.user:
    name: roboshop

- name: Clean App old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create App directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /tmp/{{component}}.zip
    remote_src: yes


