- name: Mysql setup
  hosts: all
  become: true
  tasks:
    - name: Copy mysql repo file
      ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

    - name: Disable default mysql version
      ansible.builtin.shell: yum module disable mysql -y

    - name: Install mysql server
      ansible.builtin.yum:
        name: mysql-community-server 
        state: installed

    - name: Restart mysql
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes

    - name: Set Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ${mysql_root_password}
      
    
      
